export * from './receitas.component';
export * from './receitas.module';
export * from './receitas-routing.module';
export * from './feijoada';
export * from './pernil';
export * from './quibe';
export * from './tortapalm';
export * from './espaguetecarbo';
export * from './strogonoff';